title: Terry小屋
author:
    name: terryoy
    email: "terry.ouyang@gmail.com"

description:
    

show_excerpts: true


theme: minima

#plugins:
#    jekyll-remote-theme

#remote_theme: benbalter/retlab
